### ISSUE TITLE
Null pointer exception error

### ISSUE THREAD

**Issue by impratik7** [DulLabs/bhai-lang#100]
### Description

Null pointer exception could also be renamed to for more meme potential..
![FNvZJ6SVQAAKITh](https://user-images.githubusercontent.com/38047130/158071244-b03bfa5b-7433-4a1c-ac97-8ce96ba14030.jpg)

### Domain

Develop

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by abhi-simform** [comment]
Excellent suggestion
