### ISSUE TITLE
Issue with playground code editor on bhailang.js.org

### ISSUE THREAD

**Issue by Ajinkya2000** [DulLabs/bhai-lang#104]
### Description

- Cursor position not proper wrt the word being typed.
- Syntax highlighting makes other bigger smaller, i.e until a particular word is not keyword it's font size is incosistent with the font size of the keyword.

**Requirements**
Need the repository for the website.

### Domain

Other

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by avinashchandan12** [comment]
bht mast kaam krta hai bhaii

**Comment by ankitchouhan1020** [comment]
Resolved. It was due to different font family in editor. Closing this.
