### ISSUE TITLE
Add support for 'beda gark'

### ISSUE THREAD

**Issue by mehulbaid** [DulLabs/bhai-lang#110]
### Description

Add support for `beda gark` for try-catch `bhai yeh kar`, `beda gark` (try - catch)

```
bhai yeh kar
         bhai ye hai a = 10;
         bhai ye hai b = 10 + (15*20);
         bol bhai "b is greater than a";
beda gark (err)
         bol bhai err
```

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ranupratapsingh** [comment]
duplicated by #115

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
