### ISSUE TITLE
Support for "gol chakkar" while true loop

### ISSUE THREAD

**Issue by vibhubithar** [DulLabs/bhai-lang#112]
### Description

DescriptionSupport for "gol chakkar" while true loop

### Domain

Bhai Lang

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
