### ISSUE TITLE
Support for "Pata nai bhai"!!!

### ISSUE THREAD

**Issue by divshekhar** [DulLabs/bhai-lang#113]
### Description

Support for Null or Undefined!

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ankitchouhan1020** [comment]
No future plan to implement this.

Thanks
