### ISSUE TITLE
Support for Try Catch Finally block "Try kar bhai, pakad bhai, sab theek hai bhai"

### ISSUE THREAD

**Issue by souvikinator** [DulLabs/bhai-lang#115]
### Description

**try**: `try kar bhai`
**catch**:`pakad bhai`
**finally**:`sab theek hai bhai`
**lafda**: `error`
```
try kar bhai {

 // kuch kaam kar bhai 

} pakad bhai (lafda) {

 // lag gye bhai ;-;

} sab theek hai bhai {
 
// aage badh

}
```

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by amolkalekar** [comment]
another option would be for Try Catch Finally block
bhai tu bhid...panga hua... niptalo sab

**Comment by shre-verse** [comment]
Try - `tu tension na le bhai`
catch XYZ exception - `XYZ sambhal lega tera bhai`
catch all - `bhai tu kar kya raha hai`

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
