### ISSUE TITLE
Support for try catch "isko dekh bhai"

### ISSUE THREAD

**Issue by piyushdhodiyal11** [DulLabs/bhai-lang#118]
### Description

for 
try {}
catch(){}
finally{} -> 
isko dekh bhai { // try block } 
pakad bhai (//exception) {//exception block} 
akhir me bhai {//final block }

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ankitchouhan1020** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.

Thanks.
