### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Prajwal-Ukhalkar** [DulLabs/bhai-lang#119]
### Description

Hi bro .... I want to make my final year project like this one. Can you please help me how should I do it. Which resources should i follow. Please give me the guidence.

Thank you

### Domain

Bhai Lang

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ankitchouhan1020** [comment]
So, the process is quite simple - You first have to decide your grammar and then create a tokenizer for tokenization. The purpose of a tokenizer would be to break your code into smaller tokens that you can parse. Then the parser comes into the picture - we created a recursive descent parser for this, which is a top-down parser and uses look ahead for predictive parsing. The parser will convert your code into an AST and after that, you can just create a simple interpreter to interpret your language. Of course, there are some edge cases and other details, but on a high level, this is the process.

Also, if you want to learn more about recursive descent parser then here's a good Udemy course that you can follow - https://www.udemy.com/course/parser-from-scratch/
