### ISSUE TITLE
Add Support For Runtime limit exceed error: "Emotional Damage"

### ISSUE THREAD

**Issue by skdotv** [DulLabs/bhai-lang#120]
### Description

Add Error for run-time limit exceed with "Emotional Damage

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by MrSunshyne** [comment]
"Emotional Atyachaar"
