### ISSUE TITLE
Change Request: Change Exception error text to "Bhai kia kar rha hai tu"

### ISSUE THREAD

**Issue by ismailfarooq** [DulLabs/bhai-lang#121]
### Description

The Following error text should be changed to **Bhai kya kar rha hai tu** to look funnier following the meme trend

![MicrosoftTeams-image](https://user-images.githubusercontent.com/30401205/158132858-a9b433f0-c8bf-4341-a41e-9f813d33f33e.png)

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by mryalamanchi** [comment]
Can we change it to "Bhai kya kar rha hai?"
