### ISSUE TITLE
Dena bhai for import 

### ISSUE THREAD

**Issue by shivam-s16** [DulLabs/bhai-lang#129]
### Description

Using  dena bhai  for importing any thing 

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by sanskaromar** [comment]
Alternate Syntax for imports at #97

**Comment by ankitchouhan1020** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
