### ISSUE TITLE
Change `hi bhai` to `namaste bhai`

### ISSUE THREAD

**Issue by damooo** [DulLabs/bhai-lang#133]
### Description

It will be much more indic, if we can say `namaste bhai` instead of `hi bhai`

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by MrSunshyne** [comment]
I suggest "arre bhai"

**Comment by ayushmankumar7** [comment]
Ab Bhai ko Namaste kaun bolta hai ? 😂

**Comment by bigansh** [comment]
Yes. Also, change `bye bhai` to `chal bhai` or `badme milte hai bhai`.

**Comment by impratik7** [comment]
Another suggestion can be `kya bol rha bhai` 😆

**Comment by ayushmankumar7** [comment]
Yeah it can be 
```
Ae Bhai
     
Chal bhai
```

**Comment by MrSunshyne** [comment]
I like "chal bhai"
