### ISSUE TITLE
division by zero 

### ISSUE THREAD

**Issue by niksanand1717** [DulLabs/bhai-lang#134]
### Description

`DivisionByZeroException`

it shows `Infinity`

mere khayal se

`bhai zero se divison kaha`

and missing semi-colon ka

`bhai semi-colon lga de`

should be good......must change to something better if required

### Domain

Bhai Lang

### Type of Contribution

Refactoring

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by aniketsingh0104** [comment]
Fixed : https://github.com/DulLabs/bhai-lang/pull/91
