### ISSUE TITLE
"Nikal bhai" for return statement

### ISSUE THREAD

**Issue by neemagaurav1996** [DulLabs/bhai-lang#135]
### Description

Using nikal bhai for returning from a function

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by shmehdi01** [comment]
it should be PEHLI FURSAT ME NIKAL

**Comment by rajaghan** [comment]
How about the following ?
return - laut bhai
exit - nikal bhai

**Comment by zaid-ahmad** [comment]
Can be-
return: aa bhai
exit: ja bhai

**Comment by ankitchouhan1020** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.

Thanks
