### ISSUE TITLE
Change Comment Text to Bhai yaha Code likh 

### ISSUE THREAD

**Issue by ayushmankumar7** [DulLabs/bhai-lang#136]
### Description

It's written 
```
hi bhai 
  // write code here
bye bhai
```

I am suggesting to change it to `// bhai yaha code likh`

### Domain

Other

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by Urjaswi-2655** [comment]
Hi, @ayushmankumar7 I want to work on this issue.
This would be my first Pull Request , pls help me to do it.
Thanks .
 I read Code of Conduct.
Just confirming, I have to change readme from  // write code here to // bhai yaha code likh , Right?
I will send you the steps I followed before pushing my PR. Thanks

**Comment by ayushmankumar7** [comment]
Oh No! I am so sorry mate :( . 
I already made a PR an hour ago.

**Comment by Urjaswi-2655** [comment]
Yeah I have seen , No problem. 
But can you help me how to commit , I have cloned repo
now what should be next.
I am not able to understand contribution.md
How should I move to readme and change it ?
I will try it on my terminal,
I will not make a PR

**Comment by Urjaswi-2655** [comment]
I have followed till step 2.  (from Contribution.md)
What to do next?

**Comment by ayushmankumar7** [comment]
Sure!

**Comment by ayushmankumar7** [comment]
So since you are a new contributor, you need not write `git remote update`, and the following 2 commands. 
In Step 3, you need to create your own branch. 
so git checkout -b "your_branch_name". This will create a branch(copy of the project within your forked project). 
Make your changes there and then do the usual "add,commit,push" and make a PR.

**Comment by Urjaswi-2655** [comment]
So git checkout -b "your_branch_name".  Done
How to move to readme.md  from my branch and update it like you did.
After that I think I understood this process"add,commit,push" and make a PR.

**Comment by Urjaswi-2655** [comment]
![Screenshot (1595)](https://user-images.githubusercontent.com/65727814/158201926-1c91b793-7e44-4bcc-9560-9c7fbbfe88d3.png)
@ayushmankumar7 I am here now

**Comment by ayushmankumar7** [comment]
OKay. So let's assume your branch name is "ABC". 
In branch "ABC" make all your changes(just make whatever changes you wanna make). 
Do the usual add and commit. 
Once done, try pushing. 
Once successfully pushed, Go to your Forked Branch on Github. You can see your branch name. 
Now if you want to make an internal PR and go to Pull Request -> Create a Pull Request -> Set the base as whatever branch you wanna update and keep the latter as "ABC". 

If you wanna make a PR to the main REPO, you need not update your internal branches, Github will automatically figure out

**Comment by ayushmankumar7** [comment]
In case github doesn't do that, keep the base as "DulLabs/bhai-lang" branch develop and your head as "Urjaswi-2655/bhai-lang" branch ABC. 

I hope this helps.

**Comment by ayushmankumar7** [comment]
Now the author of this repo is either gonna praise me for opening this Gurukul within this Issue or gonna mock me on my layman's way of explaining "how to contribute to Open Source repo" :)

**Comment by Urjaswi-2655** [comment]
Thanks @ayushmankumar7 . 
You will be praised definitely . 
I will add one more comment with just steps I would have to follow next (to confirm I have understood) , Then I will not disturb you, Thanks

**Comment by Urjaswi-2655** [comment]
@ayushmankumar7 
I have to do
git branch urjaswi 
make changes like updating readme ? But how will I update my readme here 
git add.
git commit -m "Updated Readme"
git push origin urjaswi 
Then move to forked repo and click on compare and pull button right?
Create pull request

**Comment by ayushmankumar7** [comment]
Yes!

**Comment by ayushmankumar7** [comment]
![image](https://user-images.githubusercontent.com/41910134/158208930-ea346407-c9ea-4616-98bc-f42444dff2a1.png)
Bas make sure ki yeh sb parameters sahi hai while you make the PR

Base will be original Repo develop branch, head will be your repo, your custom branch

**Comment by Urjaswi-2655** [comment]
Thik Hain @ayushmankumar7  Thanks 😊

**Comment by ayushmankumar7** [comment]
Ab **Bhai** ko Thanks bolega 😂

**Comment by prkhrv** [comment]
@ayushmankumar7 Respect Bhai !!
