### ISSUE TITLE
Add support for const keyword

### ISSUE THREAD

**Issue by swarajpande5** [DulLabs/bhai-lang#138]
### Description

`pakka bhai yeh hai a = 20;`
"pakka" can be used similar to const keyword.

### Domain

Bhai Lang

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by aditya-vector** [comment]
How about `bhai ye hai patthar ki lakir a = 20`

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
