### ISSUE TITLE
Support for `kaam kar bhai`

### ISSUE THREAD

**Issue by nitch193** [DulLabs/bhai-lang#144]
### Description

It will be used as function blocks, e.g.
`kaam kar bahi(params) {
   //yaha lih bhai
}`
This will help in making this language more complete.

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by Ashutosh-bh** [comment]
instead it can be 

`bhai ek kam kar functionName(params) { //something}`

ex -:

`bhai ek kam kar battiBujha() {
     bol bhai "batti Gull"
}`

**Comment by aniketsingh0104** [comment]
Some people are already working on it - https://github.com/DulLabs/bhai-lang/issues/170
