### ISSUE TITLE
Support for try catch 

### ISSUE THREAD

**Issue by sarsharma** [DulLabs/bhai-lang#147]
### Description

We could have support for try catch like this 

```
ab ye krke dikhao bhai { 
// try block code here 
}
mujhse nhi hua bhai(sorry) {
bol bhai sorry;
}
```

### Domain

Bhai Lang

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
