### ISSUE TITLE
Add delay (RUKO ZARA SABAR KRO)

### ISSUE THREAD

**Issue by shmehdi01** [DulLabs/bhai-lang#148]
### Description

Description
Add delay as RUKO ZARA SABAR KRO

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by frankhart2018** [comment]
@shmehdi01 bhai this seems to be something which should be done in a package which can be imported like time in python, so that users can do something like time.sleep(10). Also, zara is an arbitrary time, I would rather propose - "Ruko bhai 10 seconds" where the last token can be seconds, milliseconds, minutes, etc.

**Comment by amalgawa** [comment]
ruko zara could be the function name and sabar_karo could be the variable name. 
i.e `ruko zara (sabar_karo)` where sabar_karo is time in seconds.

**Comment by NiinS** [comment]
>  "Ruko bhai 10 seconds"

Fair point.. Can we also look at using 'pal' as the well known synonym for seconds in the spirit of Bhailang.

e.g.

"Ruko bhai do pal" is same  "Ruko bhai 2 seconds"

**Comment by swapnilbarwat** [comment]
> > "Ruko bhai 10 seconds"
> 
> Fair point.. Can we also look at using 'pal' as the well known synonym for seconds in the spirit of Bhailang.
> 
> e.g.
> 
> "Ruko bhai do pal" is same "Ruko bhai 2 seconds"

I feel this would be little too much to remember and chances are people will prefer default implementation. Like dict.get(key) method in Python. dict[key] is more easy to remember than the former one.

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
