### ISSUE TITLE
Bhai community on discord

### ISSUE THREAD

**Issue by frankhart2018** [DulLabs/bhai-lang#152]
### Description

Hi, is there a community for all the bhais to collaborate on this project (on discord or any other platform)? 

### Domain

Bhai Lang

### Type of Contribution

Others

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by iamDyeus** [comment]
Yeah that Would be cool

**Comment by tbhaxor** [comment]
@ristri @aniketsingh0104 Bhai log koi plan hai iska? Ya fir GitHub discussions?

**Comment by tbhaxor** [comment]
Hey bhai log. Come and join the bhai community here

https://discord.gg/KBKawgCKMq

**Comment by aniketsingh0104** [comment]
Already present here - https://github.com/DulLabs/bhai-lang/issues/217
