### ISSUE TITLE
Add support for the functions

### ISSUE THREAD

**Issue by tbhaxor** [DulLabs/bhai-lang#154]
### Description

Support `bhai bula {name} aur bhej {list of params}` the return statement can `bhai wapis kar {return}`

What it would look like
```
hi bhai
    bhai bula greet aur bhej name, age {
        bhai wapis kar name + age;
    }
bye bhai
```

Motivation: https://github.com/DulLabs/bhai-lang/issues/94#issuecomment-1066802303

### Domain

Bhai Lang

### Type of Contribution

Addition, Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by tbhaxor** [comment]
I always wanted to learn how languages work and this seems like a good start. Can I work on this?. It will take some time to understand and then implement.

**Comment by bhushanvaidya** [comment]
the return statment should be "ye le bhai"

**Comment by thecodacus** [comment]
added a PR for this, 
you guys can check it in preview build https://6234ac37ec8e100008f579b5--bhailang-preview.netlify.app/#playground
