### ISSUE TITLE
Add support for Object

### ISSUE THREAD

**Issue by dush-ik** [DulLabs/bhai-lang#157]
### Description

Plain objects or hashmaps are not supported yet.

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ankitchouhan1020** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.

Thanks. Closing this for now.
