### ISSUE TITLE
Add typechecking

### ISSUE THREAD

**Issue by abhayvishnoi** [DulLabs/bhai-lang#159]
### Description

Add `kaisa hai bhai variable` to print type of variable

### Domain

Develop

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ankitchouhan1020** [comment]
No current plans to add this feature in this language. May be take it in future scope.
