### ISSUE TITLE
Support for bhai padh ise

### ISSUE THREAD

**Issue by jain-neeeraj** [DulLabs/bhai-lang#162]
### Description

In case of reading from a file can we add support for "bhai padh ise"

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ankitchouhan1020** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language. Thanks.
