### ISSUE TITLE
Accept user input as "or bata"

### ISSUE THREAD

**Issue by jain-neeeraj** [DulLabs/bhai-lang#164]
### Description

To get an input from user, can we create a command with name "aur bata"

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by NiinS** [comment]
can we call it 'aur bata' since 'or' can be used for logical OR?

**Comment by jain-neeeraj** [comment]
@NiinS yeah.. it makes more sense.. it should aur bata

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
