### ISSUE TITLE
Tribute to the Ultimate bhai

### ISSUE THREAD

**Issue by jain-neeeraj** [DulLabs/bhai-lang#165]
### Description

Since most famous bhai is Sallu Bhai, can we rename a very common exception/error/warning to SalluBhai

It is up to the community to decide which exception to pick. Few ideas

- UnhandledPromiseRejectionWarning
- division by zero 

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by PureshwarGonekar** [comment]
I think this division by zero error can be rename with "bhai dhokha"

**Comment by ankitchouhan1020** [comment]
It is resolved. Thanks.
