### ISSUE TITLE
Exception as "kya kar hai tu??" instead of "kya kar raha hai tu??" missing word "raha"

### ISSUE THREAD

**Issue by decryptCipher** [DulLabs/bhai-lang#167]
There is this word "raha" is missing when the exception is thrown on the output terminal correct it as "kya kar raha hai tu??" instead of "kya kar hai tu??"

**Comment by rohit2905** [comment]
made the changes, can assign me

**Comment by PriyanshuGarg26** [comment]
I want to work on this issue, can you assign it to me.

**Comment by aniketsingh0104** [comment]
Already fixed.
