### ISSUE TITLE
Support for new and delete operator

### ISSUE THREAD

**Issue by PureshwarGonekar** [DulLabs/bhai-lang#171]
### Description

new : "peda hoja bhai"
delete : "marja bhai"

What should be best comment down.

### Domain

Bhai Lang

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by Shriya1312** [comment]
For new operator it should be "naya bana de bhai" and for delete "gayab kar de bhai"  or "yha se hata de bhai".

**Comment by 007ARK** [comment]
For delete, how about : "चुल्लू भर पानी mein doob mar bhai" 😂
