### ISSUE TITLE
TypeError - Ye sab doglapan hai 

### ISSUE THREAD

**Issue by SarthakPatidar** [DulLabs/bhai-lang#172]
### Description

Runtime exception for mis-match method argument types 

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by dhaval-shah-pratishthan** [comment]
How about

![image](https://user-images.githubusercontent.com/68225078/158522962-11c4c898-cd8d-40c7-9a3b-d6533fc7c49e.png)

**Comment by SarthakPatidar** [comment]
@dhaval-shah-pratishthan - Thank you for suggesting. This suites bhai lang more.

Most of us are getting diverted from bhai lang because of shark tank 😂
