### ISSUE TITLE
Instant Share option of Code Editor as image

### ISSUE THREAD

**Issue by purvjeja** [DulLabs/bhai-lang#178]
### Description

As language is popular for mentioning a compiler as "Bhai", then writing any "Bhai-lang" syntax for algorithmic code would be a comedy and it can be a programming memes, so by adding a share option would be easy for programming memes creator for sharing instantly as images.

### Domain

Develop

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by 007ARK** [comment]
Do you mean a pseudocode based on Bhai-lang?
That sounds fun!

**Comment by ankitchouhan1020** [comment]
Screenshot seems a simple solution here.
