### ISSUE TITLE
Support for dhaage (Threads)?

### ISSUE THREAD

**Issue by NiinS** [DulLabs/bhai-lang#179]
### Description

Can we have support for threads please? Can't imagine how it will be narrated, may be community can suggest..  

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by Aryan-Srivastava** [comment]
moh moh  ke dhage ?

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
