### ISSUE TITLE
Ashneer grover meme

### ISSUE THREAD

**Issue by pallasite99** [DulLabs/bhai-lang#181]
### Description

* Include a meme related to a shark tank india episode while displaying output
[meme](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.hindustantimes.com%2Ftrending%2Fhilarious-shark-tank-india-memes-reactions-take-over-twitter-and-instagram-101643011685245.html&psig=AOvVaw2ibFZ_LAG-80vk7SgMQ7mY&ust=1647477338950000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCLCWhsCxyfYCFQAAAAAdAAAAABAJ)

### Domain

UI/UX

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by amogh-nagar** [comment]
Hey @pallasite99 
Can i work on this issue?

**Comment by pallasite99** [comment]
Sure @Amoghtech. Most welcome!

I've already created a PR for this. You can push your changes with a PR to my fork

**Comment by pallasite99** [comment]
@Amoghtech https://github.com/DulLabs/bhai-lang/pull/182
