### ISSUE TITLE
Support for comparing `nalla`

### ISSUE THREAD

**Issue by shriaas2898** [DulLabs/bhai-lang#185]
### Description

Currently comparing `nalla` like `nalla == nalla` gives error `NallaPointerException: Nalla operand ni jamta "==" ke sath`, not sure if this is intended since even in  Typescript and JS `null == null` evaluates to `true`, so here `nalla == nalla` should evaluate to `sahi`.
I can take up this issue just need some help on how to get started.

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by aniketsingh0104** [comment]
fixed : https://github.com/DulLabs/bhai-lang/pull/219
