### ISSUE TITLE
Support for gazab or gajab

### ISSUE THREAD

**Issue by jain-neeeraj** [DulLabs/bhai-lang#187]
### Description

In case of any run time exception, we should be priting "Gajab kar diya" or "Gajab ho gaya" or "Gajab occured"

### Domain

Bhai Lang

### Type of Contribution

Addition, Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by AryanshTripathi** [comment]
For Compilation Error: "O bete moj kar di"
For Runtime Error: "Gajab, tum to bade heavy driver ho bhai"
