### ISSUE TITLE
Replace < and > with Chota hai and bada hai

### ISSUE THREAD

**Issue by m-anshuman2166** [DulLabs/bhai-lang#188]
### Description

Description

Suggestion : Replace `<` and `>` with `chota hai` and `bada hai`

### Domain

Bhai Lang

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by purvjeja** [comment]
Thoda toh programming language rhene do isko :)

**Comment by dprateek1991** [comment]
Yes, please don't change operators.

**Comment by Mapegz** [comment]
keep the operators but this can be an optional feature.
