### ISSUE TITLE
Remove semicolons necessity from bhaiLang

### ISSUE THREAD

**Issue by akgupta0777** [DulLabs/bhai-lang#189]
### Description

`;` should not be there in a toy language. People from js and ts world don't use semicolon that much.

**Suggestions**
If you found that ; is missing in code then compiler should either ignore it 
                                    OR
It should automatically place a semicolon there.

### Domain

Bhai Lang

### Type of Contribution

Addition, Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by shriaas2898** [comment]
+1

**Comment by tbhaxor** [comment]
Mai kaam kar rha hu bhai log ispe

**Comment by aniketsingh0104** [comment]
This is not a priority for us. Also, its a good practice to use explicit semicolons in js and ts also.
