### ISSUE TITLE
Successful Compilation Message

### ISSUE THREAD

**Issue by heymanishjain** [DulLabs/bhai-lang#191]
### Description

This language looks fun & great.

Once the code is successfully completed we can have **Bhai Bhai Bhai Bhai**

### Domain

Bhai Lang

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by agam778** [comment]
Or we can print something like the playground does too...
![image](https://user-images.githubusercontent.com/68941022/158737493-2bb82e2e-5f68-4bb5-9f3f-c3a6a3222ac0.png)
