### ISSUE TITLE
Bhai  bhai batana, bhai batana please

### ISSUE THREAD

**Issue by biggerinfinity** [DulLabs/bhai-lang#192]
### Description

Description
![image](https://user-images.githubusercontent.com/101240040/158734180-1c33cf82-78a1-47a7-a9bd-f6717043608f.png)

you can use this for input :)

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
