### ISSUE TITLE
Add exception handling

### ISSUE THREAD

**Issue by cicar** [DulLabs/bhai-lang#193]
Add exception handling something like this.

Bhai karke dekh

Locha hove to

Akhir me

**Comment by deepakbharadwaj** [comment]
![image](https://user-images.githubusercontent.com/32411411/158746513-19a4e5a7-bda3-443c-a63e-b76bf12aacd7.png)
We can use this for catch or for errors on syntax check in Bhai-lang

**Comment by TanishqYadav4** [comment]
Can I work on this ? I'd like to contribute ?

**Comment by rahulp772** [comment]
Add on errror something like "Bhai kuch locha hua hai"

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
