### ISSUE TITLE
Discord bot support??

### ISSUE THREAD

**Issue by Amitminer** [DulLabs/bhai-lang#195]
### Description

Addd a function to run discord bot xD 

### Domain

Bhai Lang

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by aniketsingh0104** [comment]
There is already a discord community you can check out here - https://github.com/DulLabs/bhai-lang/issues/217
