### ISSUE TITLE
Input as Bantai

### ISSUE THREAD

**Issue by divyansh0804** [DulLabs/bhai-lang#196]
### Description

Bata Na Bantai! can be used for input 

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.

**Comment by KeshavSachdeva95** [comment]
Pls bhai add this pls
