### ISSUE TITLE
[Question] How are you resolving non-npm packages like bhai-lang-parser

### ISSUE THREAD

**Issue by tbhaxor** [DulLabs/bhai-lang#199]
### Description

I am curious to know how this resolution is working as I couldn't find enough info in package.json `"bhai-lang-parser": "*"`

### Domain

Develop

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by aniketsingh0104** [comment]
We are using turborepo for this. You can read more here - https://turborepo.org/
