### ISSUE TITLE
Exception or error handling

### ISSUE THREAD

**Issue by navneetgarggate6** [DulLabs/bhai-lang#202]
### Description

Please add Watt Lag Gayi Bhai or error

### Domain

Bhai Lang

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ajeetkr-7** [comment]
For exception we can say - " Locha ho gya bhai "

**Comment by mayank11196** [comment]
I think "bhai kaand ho gaya" would be more apt

**Comment by thirdworlder** [comment]
If its exception handling block, it could be: "agar locha hua bhai"

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
