### ISSUE TITLE
In bhai-lang, shouldn't `sahi` be false and `galat` be true?

### ISSUE THREAD

**Issue by suvratapte** [DulLabs/bhai-lang#203]
### Description

I sincerely think that in bhai-lang, the meaning of True and False should be reversed.
`sahi` should be `false` and `galat` should be `true`.

Willing to make a PR if you agree with me. 😅

Feel free to reject! 😄 

### Domain

Bhai Lang

### Type of Contribution

Refactoring

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by zaid-ahmad** [comment]
No because sahi is right, so- True and galat is wrong, so- False.
