### ISSUE TITLE
Support for try-catch block with "bhai tension mat le(try) - tera bhai hai naa(catch)"

### ISSUE THREAD

**Issue by mayank11196** [DulLabs/bhai-lang#205]
### Description

Add support for try/catch block with above names!!
I have already started working on it. Assign this to me.

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
