### ISSUE TITLE
Support for Promises

### ISSUE THREAD

**Issue by shashvattrip** [DulLabs/bhai-lang#208]
### Description

Enable Promise support with creation of Promises, handling resolutions and rejections, and the finally block.

1. `bhai main dekhlunga` (new Promise())
2. `bhai dekhliya`(then())
3. `bhai nai dikh raha` (.catch())
4. `bhai bas tu dekhle` (.finally())

### Domain

Bhai Lang

### Type of Contribution

Addition

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by nair-sreerag** [comment]
how about changing point 3 to `bhai kuch gadbad hai`

**Comment by OmkarK45** [comment]
How about `naya Vada` (वादा)  for `new Promise` ?

**Comment by aniketsingh0104** [comment]
No current plans for adding support of pormises.
