### ISSUE TITLE
usko leke aa bhai <file name> for imports

### ISSUE THREAD

**Issue by aksmahajan** [DulLabs/bhai-lang#211]
### Description

hi bhai

bol bhai "Eventually project structure to banana padega to files alag alag folder me jayengi. To import karNe keliye usko leke aa bhai ekdum dhhasu rahega Bhai";

chal bhai

### Domain

Bhai Lang

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by sanikava** [comment]
or you can just say भाई देना / Bhai  dena for require

**Comment by aniketsingh0104** [comment]
No current plans to add support for imports.

**Comment by sanikava** [comment]
> No current plans to add support for imports.

after that it will be no more toy programming lang 🤣
