### ISSUE TITLE
"tu bolna bhai" for getting input

### ISSUE THREAD

**Issue by zaid-ahmad** [DulLabs/bhai-lang#213]
### Description

Description
To get an input from user, can we create a command with the name "tu bolna bhai"

### Domain

Bhai Lang

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ghoshankur** [comment]
Can we make it "bolna bhai" instead for getting input and dikha bhai for output?

**Comment by ZeroCoolHacker** [comment]
actually we are telling the program to ask for input so it should be **puch bhai**

**Comment by sanikava** [comment]
I agree with **puch bhai** because **bol bhai** is already there so it can confuse some people.

**Comment by zaid-ahmad** [comment]
> actually we are telling the program to ask for input so it should be **puch bhai**

Well, yeahh...you're right. "puch bhai" is more appropriate.

**Comment by surajmamgai** [comment]
It should be **lele bhai** and **dede bhai** for input and output respectively

**Comment by sanikava** [comment]
> It should be **lele bhai** and **dede bhai** for input and output respectively

puch for input and bol for output so i think bol is output

**Comment by thirdworlder** [comment]
"Puch bhai" could be spelled as "Pooch bhai"?

**Comment by aniketsingh0104** [comment]
No current plans to add use input.
