### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by evishalarora** [DulLabs/bhai-lang#215]
### Description

Its not an issue, but just wanted to applaud you guys. Made me laugh and also made me realize that a serious effort can make hindi as a language to code.

### Domain

Bhai Lang

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by 007ARK** [comment]
More effort will be required to make everyone agree on a single way of writing hinglish. 
You know, the "karna" vs "krna."

**Comment by zaid-ahmad** [comment]
> More effort will be required to make everyone agree on a single way of writing hinglish. You know, the "karna" vs "krna."

and "sahi" vs "shi"

**Comment by aniketsingh0104** [comment]
Thanks.
