### ISSUE TITLE
Aree bhai bhai bhai

### ISSUE THREAD

**Issue by NikhilCodes** [DulLabs/bhai-lang#218]
### Description

I hope that there isnt a throw new Error syntax yet, so can we do something like,
```
aree bhai bhai bhai
```
to throw error

### Domain

Bhai Lang

### Type of Contribution

Addition, Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by zaid-ahmad** [comment]
I think someone changed it to that Ashneer Grover meme.

**Comment by aniketsingh0104** [comment]
No recent plans to add error handling.
