### ISSUE TITLE
No Globalization? - Only Hindi speaking person can easily use this Lang?

### ISSUE THREAD

**Issue by Aravin** [DulLabs/bhai-lang#233]
No Globalization? - Only Hindi speakers can easily use this Lang?

**Comment by electrolyte-orb** [comment]
Nope.

**Comment by ankitchouhan1020** [comment]
No future plan to support globalization. However some fork repos are working or playing around their native language. https://github.com/sheshavpd/gurulang

Thanks, closing this.

**Comment by Aravin** [comment]
Can I work on Tamil language?

**Comment by ankitchouhan1020** [comment]
You can fork the repo and create your own version.

**Comment by shankarkrupa** [comment]
Forked for Tamil at https://github.com/shankarkrupa/nanba-lang . @ankitchouhan1020 - could you consider moving the hardcoded strings to a dynamically loaded file at build time and also the do something for the constants+keywords in bhailangspec.ts and syntax.ts files? If this is not in the roadmap, I understand perfectly this might deter the progress of the language from progressing in the core areas. However, please do confirm.

**Comment by ankitchouhan1020** [comment]
I think most of the language spec are already in a constant file which is pretty easy to change. Rest are mostly test files.  This feature is not in pipeline anytime soon.

Congrats on creating your own version from it. 🎉

**Comment by shankarkrupa** [comment]
@ankitchouhan1020 Okay. I think it would create fork bloats as these forks can never be merged back with a PR to this main repository. If we have a way to dynamically load the constants, examples with a template placeholder, and the regex it would be really good. I can give a PR ensuring there are sufficient unit tests if you can merge it after review.
