### ISSUE TITLE
Feature Request: Kindly add autocomplete text prediction during the syntax

### ISSUE THREAD

**Issue by nitinkumar30** [DulLabs/bhai-lang#260]
### Is your feature request related to a problem? Please describe.

When we write any syntax like ```bol bhai```, we may have a suggestion for the correct syntax so that we can just press ```TAB``` to autocomplete the correct syntax instead of writing whole syntax i.e. ```bol bhai```. 

### Describe the solution you'd like.

We may have a autocomplete/suggested text during the writing of syntax in bhailang.

### Describe alternatives you've considered

We can have a prediction like google mails which allows having **inactive syntax** and will be autocompleted after pressing ```TAB```.

### Additional context.

Thanks for making this awesome programming language. I've also thought of making one during my graduation but I was lacking in proper knowledge. Just learning it & waiting for companies to adopt it. Will apply for the same by saying ```hire kar na bhai```.

**Comment by tbhaxor** [comment]
That is part of the external completion service related to a text editor or IDE. Please checkout this link for more information https://marketplace.visualstudio.com/items?itemName=exploorex.bhailangofficial

**Comment by nitinkumar30** [comment]
Thanks @tbhaxor . Understood your point.
