### ISSUE TITLE
Where is the executable outputted?

### ISSUE THREAD

**Issue by Lioncat2002** [DulLabs/bhai-lang#269]
I built the project using `npm build` but I cannot find where the executable got outputted?

**Comment by tbhaxor** [comment]
Check for the bin directory in the cli package. The configuration can be found [here](https://github.com/DulLabs/bhai-lang/blob/develop/packages/cli/package.json#L8)

**Comment by Lioncat2002** [comment]
Ahhh found it thnx :)

**Comment by Lioncat2002** [comment]
oh I have another question
so I need to run with `node index.js test.bhai` how do I run it as `bhailang test.bhai`?

**Comment by tbhaxor** [comment]
You can use both. Since `bhailang` is not in the PATH, you have to use `./bhailang test.bhai`

**Comment by Lioncat2002** [comment]
running with ./bhailang actually shows not found
![image](https://user-images.githubusercontent.com/74904820/162678440-f3483a3a-baa2-4ab2-8551-28dee00bc866.png)

**Comment by tbhaxor** [comment]
The bhailang bin will be available when you install the package for example as you do installs for `npm i -g eslint`. In this case you are supposed to use node

**Comment by Lioncat2002** [comment]
ahhh gotcha
