### ISSUE TITLE
Q.  How to delete it from termux

### ISSUE THREAD

**Issue by Rakeshyadav-19** [DulLabs/bhai-lang#283]
### Describe what you are trying to do and why it is not optimal.

I installed it in termux using

npm i -g bhailang

Now how do I unistall it

**Comment by tbhaxor** [comment]
```console
npm uninstall -g bhailang
```

**Comment by Rakeshyadav-19** [comment]
okay thanks

**Comment by Rakeshyadav-19** [comment]
Done
