### ISSUE TITLE
Whats the use-case for NodeType.InitStatement

### ISSUE THREAD

**Issue by vipulbhj** [DulLabs/bhai-lang#65]
Hey folks, great work in this.

I am curious, there is a specific reason why the Program contains an InitStatement as it's start block ?

From a brief look I have had till now, this seems it can be removed from the AST, but would love to learn more on why is this designed like this :)

**Comment by ristri** [comment]
You are right, there is no need for InitStatement and it can be removed from the AST, the only reason it exists is because we wanted the program to start with `hi bhai` and end with `bye bhai` . This has something to do with the inside joke that led to creation of this language.
