### ISSUE TITLE
docs if any?

### ISSUE THREAD

**Issue by maheswarantp** [DulLabs/bhai-lang#66]
Any docs for this if provided will be helpful. Also, do mention planned features so as to contribute if possible in some way

**Comment by aniketsingh0104** [comment]
If you want docs around usage then you can find it here in the readme - https://github.com/DulLabs/bhai-lang#documentation and also in website https://bhailang.js.org/ . 

However, if you want docs around the code of the language itself, then I think the code is pretty self-explanatory. Go through the code once, and you'll probably understand if you have basic understanding of parser & interpreter. 

We don't have any planned features as of now, but contributions are always welcome. Thanks.

**Comment by aniketsingh0104** [comment]
Duplicate of - https://github.com/DulLabs/bhai-lang/issues/70
