### ISSUE TITLE
Support for "Bata Bhai"

### ISSUE THREAD

**Issue by ranupratapsingh** [DulLabs/bhai-lang#75]
Hey all, I just got to know about this today. 
Right now I don't see taking input as a feature. I want to propose a "Bata bhai"  or "pooch bhai" statement to take input.

What say bhai log ?

**Comment by neophyt3** [comment]
ek number bhai 🤣

**Comment by thatfreakcoder** [comment]
```de na bhai``` FTW

**Comment by harshkanjariya** [comment]
Can I add input support if anyone haven't taken this issue?

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
