### ISSUE TITLE
Support for Kuch bhi

### ISSUE THREAD

**Issue by ankiteshjha** [DulLabs/bhai-lang#76]
This is fun!

can we have error handling via "Kuch bhi"

**Comment by mehtakartik** [comment]
Kuchh bhi sounds more apt as a command to a random number generator to hand out a new onw

**Comment by AmiyaDas** [comment]
@mehtakartik right this can be the random number method 👍🏻

**Comment by RaviGehlot1** [comment]
For error handling we can have 'Ye to gya'

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
