### ISSUE TITLE
how to run the project

### ISSUE THREAD

**Issue by adamsyy** [DulLabs/bhai-lang#80]
i tried to run the project, installed turbo and ran 'turbo run dev --parallel' but local host not opening up, donno at which port is it running... can anyone help me out

**Comment by adamsyy** [comment]
@shubh0107 @ristri @aniketsingh0104 
@ankitchouhan1020

**Comment by ankitchouhan1020** [comment]
```
npm i
npm run dev
```
docs will run on localhost:3000

**Comment by adamsyy** [comment]
i am getting this error on running npm run dev
![e](https://user-images.githubusercontent.com/75473780/158057296-3e7d08e2-796b-4b3c-b51c-466e6faa8a81.png)

**Comment by ristri** [comment]
```
npm i
npm run build 
npm run dev
```
@ankitchouhan1020  we can mention these instructions in a CONTRIBUTING.md file

**Comment by adamsyy** [comment]
thanks man!
