### ISSUE TITLE
Support for "Are Bhai Bhai Bhai"

### ISSUE THREAD

**Issue by rachitag112** [DulLabs/bhai-lang#82]
This is amazing!!

We can have "Are Bhai Bhai Bhai" for error statements

**Comment by ankitchouhan1020** [comment]
<img width="943" alt="Screenshot 2022-03-13 at 4 57 43 PM" src="https://user-images.githubusercontent.com/26669522/158057266-d65ac1da-78fc-4887-ad68-48319d678f75.png">

Apun ne intzaam kr rkha hai bhai.. :D
