### ISSUE TITLE
Support for error messages

### ISSUE THREAD

**Issue by chauhanprateek89** [DulLabs/bhai-lang#83]
Currently errors like "divide by zero" gives out message as "infinity".

There is potential here to expand on this, like - 
"Bhai ye kya kiya"
"Bhai aise nahi hota"
"Bhai ye kya kar diya"

**Comment by Deep-Codes** [comment]
Would work on this

What should be an idea message?

thinking of Bhai Bhai Bhai...

wdyt?

**Comment by chauhanprateek89** [comment]
Bhai Bhai Bhai could serve as a good starting point as a generic error message instead of "infinity". We can then lean towards more custom messages as we move forward. 
What's your take?

**Comment by Deep-Codes** [comment]
> Bhai Bhai Bhai could serve as a good starting point as a generic error message instead of "infinity". We can then lean towards more custom messages as we move forward. What's your take?

Check out the PR have added ^

<img width="1029" alt="Screenshot 2022-03-13 at 6 12 58 PM" src="https://user-images.githubusercontent.com/61158210/158059868-818841b9-8224-4147-9448-c1da9dbe0d0a.png">

**Comment by chaidosa** [comment]
Suggestion:
Hey error message could be `bhai ye kya kar rha hai tu!!`

**Comment by chauhanprateek89** [comment]
We should be gender-neutral with how we design this as we want maximum adaptation. Just a thought.

**Comment by Kadam-Tushar** [comment]
Another suggestion: 
Bhai kya kar raha hai tu?

**Comment by aniketsingh0104** [comment]
Already Fixed.
