### ISSUE TITLE
Add copy to clipboard icons on landing page documentation

### ISSUE THREAD

**Issue by ankitchouhan1020** [DulLabs/bhai-lang#84]

**Comment by shubh0107** [comment]
I can work on this, if no one has taken this up.

**Comment by ankitchouhan1020** [comment]
sure, thanks

**Comment by manavsiddharthgupta** [comment]
if anyone is not doing can you assign me I would like to take this issue?

**Comment by shubh0107** [comment]
Hi Manav, i have already raised a PR for this issue, its already assigned to me.
However there are a lot of other issues that you can try your hands on.

Thanks!
