### ISSUE TITLE
Support for Ruk Ja Bhai 

### ISSUE THREAD

**Issue by Raj2503** [DulLabs/bhai-lang#89]
### Description

Petition to add `Ruk Ja Bhai` or `Tham Ja Bhai` for `break` statement 😂

### Domain

Bhai Lang

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ankitchouhan1020** [comment]
`bas kar bhai` is already there. Enjoy 😆
