### ISSUE TITLE
Can we start contributing

### ISSUE THREAD

**Issue by Longju000** [DulLabs/bhai-lang#92]
### Description

Wanna make it a fun thing,
So if you guys are open for contribution

### Domain

Other

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ankitchouhan1020** [comment]
Hey,

Yes, we are open for contribution. Looking forword for more creative PRs.

**Comment by akki-akshat** [comment]
@ankitchouhan1020 Awesome initiative guys, I am sure this will go viral soon, I just shared it with 150+ devs

**Comment by GargDivanshu** [comment]
Hello sir, 
I want to start contributing in this project
How can we start contributing?? As of now I'm not able to understand where can I help you? Can you pls help in making it clear?

**Comment by ankitchouhan1020** [comment]
Hi @GargDivanshu, look for help-wanted or good-first-issue tags.

You will need some compiler design knowledge for contribution in the language. Otherwise you can contribute in docs or web app.
