### ISSUE TITLE
Small Suggestion :

### ISSUE THREAD

**Issue by webbdays** [DulLabs/bhai-lang#95]
I see that nalla, sahi and galat are language specific bult-in variables/macros here.
Make them _nalla, _sahi and _galat  or make them all capital to differentiate them from normal variables.

**Comment by jee1mr** [comment]
but they are like null, true and false. Even in JS, they are all small case and without an underscore.

**Comment by webbdays** [comment]
Ok.
Then they are keywords in the language.
