### ISSUE TITLE
Support for "Ye Kar lo Pehle" 

### ISSUE THREAD

**Issue by bj8798** [DulLabs/bhai-lang#97]
### Description

Import statement with the syntax as "Ye Kar lo Pehle"

### Domain

Develop

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by dar5hak** [comment]
Alternative syntax:

```
bhai 'react' se useState, useEffect le aa;
bhai 'lodash' se sab le aa; // import * as lodash from 'lodash';
```

**Comment by adityapalve** [comment]
"Ye karlo pehle" can be a good error to throw for imports.

**Comment by yogeshjain999** [comment]
> Alternative syntax:
> 
> ```
> bhai 'react' se useState, useEffect le aa;
> bhai 'lodash' se sab le aa; // import * as lodash from 'lodash';
> ```

This can be also written as

```
bhai 'react' se useState, useEffect utha le;
bhai 'lodash' se sab utha le; // import * as lodash from 'lodash';
```

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
