### ISSUE TITLE
Support for input

### ISSUE THREAD

**Issue by coderGtm** [DulLabs/bhai-lang#99]
Can we use this for input?
`bhai sun variable`

**Comment by impratik7** [comment]
Great! Looks good.

**Comment by ranupratapsingh** [comment]
duplicate of #75

**Comment by ZeroCoolHacker** [comment]
actually sun bhai looks better

**Comment by coderGtm** [comment]
`Bhai sun var` sounds more programatic though

**Comment by aniketsingh0104** [comment]
No current plans to add this feature in this language as this will lead to more complexities in this toy language.
